package errcode

var (
	NoPermission         = NewError(20007, "No Permission")
	ErrorCaptchaPassword = NewError(20012, "Error Captcha Password")
	TooManyLoginError    = NewError(20014, "Too Many Login Error，Please try again later")
	NicknameLengthLimit  = NewError(20020, "Nickname length 2~12")
	NoExistUserAddress   = NewError(20021, "No Exist User Address")
	NicknameDuplication  = NewError(20022, "Nickname duplication")

	CreatePostFailed  = NewError(30002, "Create Post Failed")
	GetPostFailed     = NewError(30003, "Get Post Failed")
	DeletePostFailed  = NewError(30004, "Delete Post Failed")
	LockPostFailed    = NewError(30005, "Lock Post Failed")
	GetPostTagsFailed = NewError(30006, "Get Post Tags Failed")
	VisiblePostFailed = NewError(30012, "Visible Post Failed")
	UserHasRetweeted  = NewError(30015, "User has retweeted")

	GetCommentsFailed   = NewError(40001, "Get Comments Failed")
	CreateCommentFailed = NewError(40002, "Create Comment Failed")
	GetCommentFailed    = NewError(40003, "Get Comment Failed")
	DeleteCommentFailed = NewError(40004, "Delete Comment Failed")
	CreateReplyFailed   = NewError(40005, "Create Reply Failed")
	GetReplyFailed      = NewError(40006, "Get Reply Failed")
	MaxCommentCount     = NewError(40007, "Max Comment Count")

	RedpacketHasBeenCollectedCompletely = NewError(50001, "It has been collected completely")
	RedpacketAlreadyClaim               = NewError(50002, "Already claim")

	GetCollectionsFailed = NewError(60001, "Get Collections Failed")

	CreateDaoFailed       = NewError(80001, "Create DAO Failed")
	GetDaoFailed          = NewError(80002, "Get Dao Failed")
	UpdateDaoFailed       = NewError(80003, "Update DAO Failed")
	DaoNameDuplication    = NewError(80004, "DAO name duplication")
	NoExistDao            = NewError(80005, "DAO not found")
	SubscribeDAO          = NewError(80006, "Subscribe DAO Failed")
	DAONothingChange      = NewError(80007, "DAO Nothing Change")
	AlreadySubscribedDAO  = NewError(80008, "Already Subscribed DAO")
	CreateChatGroupFailed = NewError(80009, "Create Chat Group Failed")
	UpdateChatGroupFailed = NewError(80010, "Update Chat Group Failed")

	PayNotifyError = NewError(90001, "Pay notify Failed")

	MsgListFailed           = NewError(100001, "Failed to get the message list")
	MsgCountFailed          = NewError(100002, "Failed to get the messages count")
	GetMsgFailed            = NewError(100003, "Get  message failed")
	DeleteMsgFailed         = NewError(100004, "Failed to delete message")
	MsgSendLastFailed       = NewError(100005, "Failed to get the last message send")
	MsgSendListFailed       = NewError(100006, "Failed to get the list of messages sent")
	MsgSendCountFailed      = NewError(100007, "Failed to get the messages sent count")
	GetMsgSendFailed        = NewError(100008, "Get send message failed")
	DeleteMsgSendFailed     = NewError(100009, "Delete send message failed")
	GetMsgReadFailed        = NewError(100010, "Get message read failure")
	GetMsgUnReadCountFailed = NewError(100011, "Failed to get message unread")
	CreateMsgReadFailed     = NewError(100012, "Create message read failure")
	UpdateMsgReadFailed     = NewError(100013, "Update message read failure")
	DeleteMsgReadFailed     = NewError(100014, "Delete message read failure")
	MsgSysListFailed        = NewError(100015, "System message fetch failure")
	MsgSysCountFailed       = NewError(100016, "Failed to get system message count")

	GetOrganFailed = NewError(110001, "Get organizational failure")
)
